######################### site variables ##############################
# customize your color and font from here.
[params.variables]
primary_color = "#0AA8A7"
text_color = "#777"
text_color_dark = "#222"
body_color = "#fff"
border_color = "#ECECEC"
black = "#000"
white = "#fff"
light = "#EDF6F5"
